### ISSUE TITLE
Failed to load correctly MC 1.19.1 Forge 42.0.1

### ISSUE THREAD

**Issue by HarryPlopper91** [shedaniel/rare-ice#12]
**Minecraft v1.19.1**
**Forge v42.0.1**

`Rare Ice (rare_ice) has failed to load correctly`
`java.lang.NoSuchFieldError: BLOCK_ENTITIES`

[PasteBin](https://pastebin.com/N1mge6cG)

**Comment by shedaniel** [comment]
Stop opening issues of unsupported Minecraft versions, it will eventually be ported

**Comment by HarryPlopper91** [comment]
Stop posting it as available for 1.19.1 if your code is not ready for it... SMH, literally shows on CurseForge as it was released by YOU 6/30/2022 for game version 1.19.1. Check your publishing settings...

![Screenshot 2022-07-31 043939](https://user-images.githubusercontent.com/98628933/182017979-f0488f1d-2fae-45c3-a53f-f7b63b49bb6d.png)
![Screenshot 2022-07-31 045115](https://user-images.githubusercontent.com/98628933/182018478-9a4c7ba2-8ed9-4bb9-8264-12ffcbe5750a.png)

**Comment by HarryPlopper91** [comment]
Which is odd, with 1.19.1 not having been released till the 27th of July. You might want to double check your publish settings on Curseforge so you stop getting these issue reports. That is most likely why it keeps happening.

**Comment by shedaniel** [comment]
It was a Forge 1.19 change that broke everything, I have updated that now.

**Comment by HarryPlopper91** [comment]
It happens. Looking forward to adding it to our pack whenever your ready.
