### ISSUE TITLE
Compat with 1.12.2?

### ISSUE THREAD

**Issue by Geezt435** [shedaniel/rare-ice#3]
I know that modding in 1.12.2 is very much hard but is it possible in the future this gonna be backported to 1.12.2? If it isn't gonna be backported, would it work in the forge?

**Comment by ramidzkh** [comment]
why would you put ice in the forge

**Comment by jearmstrong21** [comment]
🐸

**Comment by shedaniel** [comment]
ok i will port this to fabric 1.12.2

**Comment by shedaniel** [comment]
yea I don't mind backporting it to 1.12, I've already started working on it for you, but sadly it cant be on forge

**Comment by Geezt435** [comment]
Oh no, I don't even use Fabric for mods

**Comment by Geezt435** [comment]
Everytime I download one of fabric mod my game starts getting confusing, freezes etc, oof
