### ISSUE TITLE
Crash on Minecraft 1.16.3

### ISSUE THREAD

**Issue by crabdancing** [shedaniel/rare-ice#6]
See [log](https://paste.ee/p/xMlzH) here.

Seems to be a result of `RegistryEntryAddedCallback.event(Registry.BIOME).register((i, identifier, biome) -> handleBiome(biome));`

**Comment by shedaniel** [comment]
outdated version of rare ice

**Comment by crabdancing** [comment]
@shedaniel whoops! Looks like I downloaded the wrong version from Curseforge. Sorry about that. :)
