### ISSUE TITLE
unable to edit the rare-ice chance

### ISSUE THREAD

**Issue by nt1513** [shedaniel/rare-ice#9]

**Comment by shedaniel** [comment]
You have to edit the config file, please check or give more context.

**Comment by nt1513** [comment]
Shedaniel since I'm not on a computer on it I am unable to modify the Json file and there's absolutely no way to modify it for me anyways because I'm on Windows 10

**Comment by shedaniel** [comment]
it's... not.. a json file? and how does windows 10 make it impossible to edit a java properties file, eh???

**Comment by nt1513** [comment]
> it's... not.. a json file? and how does windows 10 make it impossible to edit a java properties file, eh???

I know I am unable to see you it's because it's exported in a regular text file and I am unable to find out which line to edit it's probably in bace 64 or base 128

**Comment by shedaniel** [comment]
it's utf-8

**Comment by nt1513** [comment]
ok
